"""create intakes table

Revision ID: 002_create_intake
Revises: 001_create_users
Create Date: 2025-01-01 00:01:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '002_create_intake'
down_revision = '001_create_users'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intakes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('situation_type', sa.Enum('EVICTION_NOTICE', 'BEHIND_RENT', 'LEASE_VIOLATION', 'PREVENTIVE', 'LOCKOUT', 'UTILITY_SHUTOFF', name='situationtype_enum'), nullable=False),
    sa.Column('has_received_notice', sa.Boolean(), nullable=False),
    sa.Column('urgency_days', sa.Integer(), nullable=True),
    sa.Column('income_monthly', sa.Integer(), nullable=True),
    sa.Column('household_size', sa.Integer(), nullable=False),
    sa.Column('has_children', sa.Boolean(), nullable=False),
    sa.Column('has_disability', sa.Boolean(), nullable=False),
    sa.Column('is_domestic_violence', sa.Boolean(), nullable=False),
    sa.Column('prior_evictions', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('EN', 'ES', name='language_enum'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('ip_country', sa.String(length=2), nullable=True),
    sa.Column('session_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint('household_size >= 1 AND household_size <= 20', name='check_household_size'),
    sa.CheckConstraint('income_monthly >= 0 OR income_monthly IS NULL', name='check_income_positive'),
    sa.CheckConstraint('urgency_days >= 0 OR urgency_days IS NULL', name='check_urgency_days_positive')
    )
    op.create_index('idx_intakes_created_at', 'intakes', ['created_at'], unique=False)
    op.create_index('idx_intakes_situation_type', 'intakes', ['situation_type'], unique=False)
    op.create_index('idx_intakes_state', 'intakes', ['state'], unique=False)
    op.create_index('idx_intakes_state_situation', 'intakes', ['state', 'situation_type'], unique=False)
    op.create_index('idx_intakes_urgency_days', 'intakes', ['urgency_days'], unique=False)
    op.create_index('idx_intakes_user_id', 'intakes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_intakes_user_id', table_name='intakes')
    op.drop_index('idx_intakes_urgency_days', table_name='intakes')
    op.drop_index('idx_intakes_state_situation', table_name='intakes')
    op.drop_index('idx_intakes_state', table_name='intakes')
    op.drop_index('idx_intakes_situation_type', table_name='intakes')
    op.drop_index('idx_intakes_created_at', table_name='intakes')
    op.drop_table('intakes')
    op.execute('DROP TYPE IF EXISTS situationtype_enum;')
    # ### end Alembic commands ###
