"""create action_plans table

Revision ID: 003_create_action_plans
Revises: 002_create_intake
Create Date: 2025-01-01 00:02:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '003_create_action_plans'
down_revision = '002_create_intake'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_plans',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('intake_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('urgency_level', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='urgencylevel_enum'), nullable=False),
    sa.Column('urgency_reason', sa.Text(), nullable=False),
    sa.Column('urgency_color', sa.Enum('RED', 'ORANGE', 'YELLOW', 'GREEN', name='urgencycolor_enum'), nullable=False),
    sa.Column('action_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rights_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('documents_needed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('escalation_flag', sa.Boolean(), nullable=False),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('escalation_contact', sa.String(length=255), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('estimated_resolution_days', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('language', sa.Enum('EN', 'ES', name='language_enum'), nullable=False),
    sa.Column('claude_model_used', sa.String(length=100), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('generation_latency_ms', sa.Integer(), nullable=True),
    sa.Column('rag_chunks_used', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('retries_needed', sa.Integer(), nullable=False),
    sa.Column('raw_claude_response', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name='check_confidence_range')
    )
    op.create_index('idx_action_plans_escalation_flag', 'action_plans', ['escalation_flag'], unique=False, postgresql_where=(sa.column('escalation_flag') == True))
    op.create_index('idx_action_plans_generated_at', 'action_plans', ['generated_at'], unique=False)
    op.create_index('idx_action_plans_intake_id', 'action_plans', ['intake_id'], unique=False)
    op.create_index('idx_action_plans_urgency_level', 'action_plans', ['urgency_level'], unique=False)
    op.create_index('idx_action_plans_user_id', 'action_plans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_action_plans_user_id', table_name='action_plans')
    op.drop_index('idx_action_plans_urgency_level', table_name='action_plans')
    op.drop_index('idx_action_plans_intake_id', table_name='action_plans')
    op.drop_index('idx_action_plans_generated_at', table_name='action_plans')
    op.drop_index('idx_action_plans_escalation_flag', table_name='action_plans')
    op.drop_table('action_plans')
    op.execute('DROP TYPE IF EXISTS urgencycolor_enum;')
    op.execute('DROP TYPE IF EXISTS urgencylevel_enum;')
    # ### end Alembic commands ###
