"""create resources table

Revision ID: 004_create_resources
Revises: 003_create_action_plans
Create Date: 2025-01-01 00:03:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '004_create_resources'
down_revision = '003_create_action_plans'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.Enum('LEGAL_AID', 'RENTAL_ASSISTANCE', 'SHELTER', 'FOOD_BANK', 'MEDIATION', 'COURT', 'HOTLINE', 'UTILITY_ASSISTANCE', 'MENTAL_HEALTH', 'CHILDCARE', name='resourcetype_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('hours_of_operation', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('eligibility_notes', sa.Text(), nullable=True),
    sa.Column('income_limit_percent_ami', sa.Integer(), nullable=True),
    sa.Column('max_household_size', sa.Integer(), nullable=True),
    sa.Column('serves_undocumented', sa.Boolean(), nullable=False),
    sa.Column('serves_domestic_violence', sa.Boolean(), nullable=False),
    sa.Column('languages_supported', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('HUD', 'API_211', 'NLIHC', 'MANUAL', 'SCRAPED', name='source_enum'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resources_is_active', 'resources', ['is_active'], unique=False, postgresql_where=(sa.column('is_active') == True))
    op.create_index('idx_resources_location', 'resources', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_resources_state', 'resources', ['state'], unique=False)
    op.create_index('idx_resources_state_type', 'resources', ['state', 'resource_type'], unique=False)
    op.create_index('idx_resources_source', 'resources', ['source'], unique=False)
    op.create_index('idx_resources_type', 'resources', ['resource_type'], unique=False)
    # Add GiST index for spatial queries
    op.execute('''
        CREATE INDEX idx_resources_gist_location ON resources 
        USING GIST (ST_MakePoint(longitude, latitude)) 
        WHERE latitude IS NOT NULL AND longitude IS NOT NULL;
    ''')
    # Add GIN index for languages_supported array
    op.execute('''
        CREATE INDEX idx_resources_gin_languages ON resources 
        USING GIN (languages_supported);
    ''')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_resources_gin_languages', table_name='resources')
    op.drop_index('idx_resources_gist_location', table_name='resources')
    op.drop_index('idx_resources_type', table_name='resources')
    op.drop_index('idx_resources_source', table_name='resources')
    op.drop_index('idx_resources_state_type', table_name='resources')
    op.drop_index('idx_resources_state', table_name='resources')
    op.drop_index('idx_resources_location', table_name='resources')
    op.drop_index('idx_resources_is_active', table_name='resources')
    op.drop_table('resources')
    op.execute('DROP TYPE IF EXISTS source_enum;')
    op.execute('DROP TYPE IF EXISTS resourcetype_enum;')
    # ### end Alembic commands ###
