"""create sms_reminders table

Revision ID: 005_create_sms_reminders
Revises: 004_create_resources
Create Date: 2025-01-01 00:04:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '005_create_sms_reminders'
down_revision = '004_create_resources'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_reminders',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('intake_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('phone_hash', sa.String(length=255), nullable=False),
    sa.Column('phone_last_four', sa.String(length=4), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('reminder_type', sa.Enum('SEVEN_DAY', 'THREE_DAY', 'ONE_DAY', 'MORNING_OF', 'CUSTOM', name='remindertype_enum'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'CANCELLED', 'OPTED_OUT', name='smsstatus_enum'), nullable=False),
    sa.Column('twilio_message_sid', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sms_intake_id', 'sms_reminders', ['intake_id'], unique=False)
    op.create_index('idx_sms_pending_scheduled', 'sms_reminders', ['status', 'scheduled_at'], unique=False, postgresql_where=(sa.column('status') == 'PENDING'))
    op.create_index('idx_sms_scheduled_at', 'sms_reminders', ['scheduled_at'], unique=False)
    op.create_index('idx_sms_status', 'sms_reminders', ['status'], unique=False)
    op.create_index('idx_sms_user_id', 'sms_reminders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sms_user_id', table_name='sms_reminders')
    op.drop_index('idx_sms_status', table_name='sms_reminders')
    op.drop_index('idx_sms_scheduled_at', table_name='sms_reminders')
    op.drop_index('idx_sms_pending_scheduled', table_name='sms_reminders')
    op.drop_index('idx_sms_intake_id', table_name='sms_reminders')
    op.drop_table('sms_reminders')
    op.execute('DROP TYPE IF EXISTS smsstatus_enum;')
    op.execute('DROP TYPE IF EXISTS remindertype_enum;')
    # ### end Alembic commands ###
