"""create progress_steps table

Revision ID: 006_create_progress
Revises: 005_create_sms_reminders
Create Date: 2025-01-01 00:05:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '006_create_progress'
down_revision = '005_create_sms_reminders'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_steps',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('action_plan_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_title', sa.String(length=255), nullable=False),
    sa.Column('step_description', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('skipped_reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', 'BLOCKED', name='stepoutcome_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_plan_id'], ['action_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_plan_id', 'step_number', name='uix_action_plan_step_number'),
    sa.CheckConstraint('step_number >= 1', name='check_step_number_positive')
    )
    op.create_index('idx_progress_action_plan_id', 'progress_steps', ['action_plan_id'], unique=False)
    op.create_index('idx_progress_is_completed', 'progress_steps', ['is_completed'], unique=False)
    op.create_index('idx_progress_outcome', 'progress_steps', ['outcome'], unique=False)
    op.create_index('idx_progress_user_id', 'progress_steps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_progress_user_id', table_name='progress_steps')
    op.drop_index('idx_progress_outcome', table_name='progress_steps')
    op.drop_index('idx_progress_is_completed', table_name='progress_steps')
    op.drop_index('idx_progress_action_plan_id', table_name='progress_steps')
    op.drop_table('progress_steps')
    op.execute('DROP TYPE IF EXISTS stepoutcome_enum;')
    # ### end Alembic commands ###
