"""create rights_cards table

Revision ID: 007_create_rights_cards
Revises: 006_create_progress
Create Date: 2025-01-01 00:06:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '007_create_rights_cards'
down_revision = '006_create_progress'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rights_cards',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('language', sa.Enum('EN', 'ES', name='language_enum'), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('notice_requirement', sa.String(length=255), nullable=False),
    sa.Column('can_be_evicted_for', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cannot_be_evicted_for', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_protections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rent_control_applies', sa.Boolean(), nullable=False),
    sa.Column('just_cause_required', sa.Boolean(), nullable=False),
    sa.Column('full_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_by_model', sa.String(length=100), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state', 'language', name='uix_state_language')
    )
    op.create_index('idx_rights_is_current', 'rights_cards', ['is_current'], unique=False, postgresql_where=(sa.column('is_current') == True))
    op.create_index('idx_rights_state_language', 'rights_cards', ['state', 'language'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rights_state_language', table_name='rights_cards')
    op.drop_index('idx_rights_is_current', table_name='rights_cards')
    op.drop_table('rights_cards')
    # ### end Alembic commands ###
