"""create analytics_events table

Revision ID: 008_create_analytics
Revises: 007_create_rights_cards
Create Date: 2025-01-01 00:07:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '008_create_analytics'
down_revision = '007_create_rights_cards'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('intake_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('action_plan_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('urgency_level', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=True),
    sa.Column('ip_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_plan_id'], ['action_plans.id'], ),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_event_type', 'analytics_events', ['event_type'], unique=False)
    op.create_index('idx_analytics_state', 'analytics_events', ['state'], unique=False)
    op.create_index('idx_analytics_type_date', 'analytics_events', ['event_type', 'created_at'], unique=False)
    op.create_index('idx_analytics_user_id', 'analytics_events', ['user_id'], unique=False)
    op.create_index('idx_analytics_created_at', 'analytics_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_analytics_created_at', table_name='analytics_events')
    op.drop_index('idx_analytics_user_id', table_name='analytics_events')
    op.drop_index('idx_analytics_type_date', table_name='analytics_events')
    op.drop_index('idx_analytics_state', table_name='analytics_events')
    op.drop_index('idx_analytics_event_type', table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
