"""Initial migration

Revision ID: 000000000001
Revises: 
Create Date: 2026-06-18

"""
from alembic import op  # type: ignore[reportAttributeAccessIssue,reportMissingImports]
import sqlalchemy as sa  # type: ignore[reportMissingImports]
from sqlalchemy.dialects import postgresql  # type: ignore[reportMissingImports]

# revision identifiers, used by Alembic.
revision = '000000000001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first
    op.execute("CREATE TYPE language AS ENUM ('EN', 'ES')")
    op.execute("CREATE TYPE resourcetype AS ENUM ('LEGAL_AID', 'RENTAL_ASSISTANCE', 'SHELTER', 'FOOD_BANK', 'MEDIATION')")
    op.execute("CREATE TYPE source AS ENUM ('HUD', 'SOURCE_211', 'MANUAL')")
    op.execute("CREATE TYPE situationtype AS ENUM ('EVICTION_NOTICE', 'BEHIND_RENT', 'LEASE_VIOLATION', 'PREVENTIVE')")
    op.execute("CREATE TYPE urgencylevel AS ENUM ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')")
    op.execute("CREATE TYPE smsstatus AS ENUM ('PENDING', 'SENT', 'FAILED')")
    op.execute("CREATE TYPE outcome AS ENUM ('RESOLVED', 'ESCALATED', 'IN_PROGRESS', 'PENDING')")

    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('language', sa.Enum('EN', 'ES', name='language'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_session_token'), 'users', ['session_token'], unique=True)
    op.create_table('resources',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.Enum('LEGAL_AID', 'RENTAL_ASSISTANCE', 'SHELTER', 'FOOD_BANK', 'MEDIATION', name='resourcetype'), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('county', sa.String(length=255), nullable=True),
    sa.Column('eligibility_notes', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('HUD', 'SOURCE_211', 'MANUAL', name='source'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intakes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('county', sa.String(length=255), nullable=False),
    sa.Column('urgency_days', sa.Integer(), nullable=False),
    sa.Column('income_monthly', sa.Integer(), nullable=False),
    sa.Column('household_size', sa.Integer(), nullable=False),
    sa.Column('situation_type', sa.Enum('EVICTION_NOTICE', 'BEHIND_RENT', 'LEASE_VIOLATION', 'PREVENTIVE', name='situationtype'), nullable=False),
    sa.Column('has_received_notice', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_plans',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('intake_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('urgency_level', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='urgencylevel'), nullable=False),
    sa.Column('action_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('documents_needed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rights_summary', sa.Text(), nullable=True),
    sa.Column('escalation_flag', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('raw_claude_response', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_reminders',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('intake_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='smsstatus'), nullable=False),
    sa.Column('twilio_sid', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('action_plan_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_title', sa.String(length=255), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.Enum('RESOLVED', 'ESCALATED', 'IN_PROGRESS', 'PENDING', name='outcome'), nullable=False),
    sa.ForeignKeyConstraint(['action_plan_id'], ['action_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progress')
    op.drop_table('sms_reminders')
    op.drop_table('action_plans')
    op.drop_table('intakes')
    op.drop_table('resources')
    op.drop_index(op.f('ix_users_session_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
    op.execute('DROP TYPE IF EXISTS outcome;')
    op.execute('DROP TYPE IF EXISTS smsstatus;')
    op.execute('DROP TYPE IF EXISTS urgencylevel;')
    op.execute('DROP TYPE IF EXISTS situationtype;')
    op.execute('DROP TYPE IF EXISTS source;')
    op.execute('DROP TYPE IF EXISTS resourcetype;')
    op.execute('DROP TYPE IF EXISTS language;')
